apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rosita-chatbot.fullname" . }}-question-generator
  labels:
    {{- include "rosita-chatbot.labels" . | nindent 4 }}
    component: question-generator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rosita-chatbot.selectorLabels" . | nindent 6 }}
      component: question-generator
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "rosita-chatbot.selectorLabels" . | nindent 8 }}
        component: question-generator
    spec:
      serviceAccountName: {{ include "rosita-chatbot.fullname" . }}
      {{- if .Values.securityContext.enabled }}
      securityContext: {{- omit .Values.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
{{- end }}
      containers:
        - name: question-generator
          image: "{{ .Values.questionGenerator.image.repository }}:{{ .Values.questionGenerator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.questionGenerator.pullPolicy }}
          resources:
          {{- toYaml .Values.questionGenerator.resources | nindent 12 }}
          ports: 
          {{-  range .Values.questionGenerator.service.ports }}
          - name: {{ .name }}
            containerPort: {{ .port }}
          {{- end }}
          env:
            {{ if .Values.extraEnvValues }}
            {{ toYaml .Values.questionGenerator.extraEnvValues | nindent 6  }}
            {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.azureFileStorage.mountPath}}
              name: fileshare-data
      volumes:
        - name: fileshare-data
          azureFile:
            {{- if .Values.azureFileStorage.create }}
            secretName: {{ include "rosita-chatbot.fullname" . }}
            {{- else}}
            secretName: {{ .Values.azureFileStorage.existingStorageSecret }}
            {{- end }}
            shareName: {{ .Values.azureFileStorage.storageName}}
